### ISSUE TITLE
PCRE is end of life

### ISSUE THREAD

**Issue by arkhaix** [launchdarkly/c-server-sdk#55]
**Is your feature request related to a problem? Please describe.**
I'm working on tooling to build a project based on c-server-sdk, and while figuring out how to supply the PCRE dependency, I came across its end-of-life announcement on pcre.org.

**Describe the solution you'd like**
I'd like to see this project use PCRE2 instead since it is actively maintained.

**Describe alternatives you've considered**
I'm moving forward with PCRE v8.45 regardless for now.  I'm just filing this as a heads up since it sounds like the upgrade will eventually become a requirement after somebody discovers a vulnerability in 8.45 someday.

**Additional context**
http://pcre.org
https://groups.google.com/g/pcre2-dev/c/rIsMBudCAsU

**Comment by cwaldren-ld** [comment]
Hi @arkhaix, thanks for the note. We'll look into this
.
_Filed internally as 158232._

**Comment by cwaldren-ld** [comment]
This SDK has been superceded by the [C++ Server-side SDK with C Bindings](https://github.com/launchdarkly/cpp-sdks). I'm closing this issue as we'd like to avoid anything but critical bugfixes in this repository.
